### ISSUE TITLE
[BUG]: New to you vs Previously seen

### ISSUE THREAD

**Issue by RichardGale** [MyMailProtocol/mail-app#21]
### Description of the bug

For a new account the Welcome email is under "Previously seen" even though it hasn't been read/seen.

### Steps To Reproduce

Go to Arweave.app and create a new wallet
Go to mymail and logout
Login with new wallet

### Additional Information

Found via automated testing.

**Comment by DanMacDonald** [comment]
This is a bug, but only in test environments where you are testing multiple accounts on localhost. The "unseen" flag for messages is somewhat unreliably stubbed in by storing state in local storage. So if you're using multiple wallets at the same basepath (`localhost:1984` for example) then once you've set the flag that the welcome message is read for any wallet all subsequent wallets will think you've read it as well. Only if you fully log out and clear local storage will you have the proper first time user experience.

In this case, the welcome message is really only intended for first time users, and it works for that scenario. The fix for this is to track ephemeral data like seen/unseen flags on an Inbox node (that is unique per wallet) instead of using local storage as a work around.
